name: Step 2

on:
  issues:
    types: [opened]
  workflow_dispatch:

concurrency:
  group: "step-2"
  cancel-in-progress: true

permissions:
  contents: read
  actions: write
  issues: write

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: |
          echo "${{ toJson(github) }}"
