name: check-all-steps

on:
  workflow_dispatch:
  push:

jobs:
  check-all-steps:
    runs-on: ubuntu-latest

    steps:

      - name: Maybe fail
        id: maybe-fail
        continue-on-error: true
        run: |
          echo "This is a deliberate fail"
          exit 1

      - name: Show all step results
        run: |
          echo "Outcomes: $OUTCOMES"
          echo "Message: $MESSAGE"
        env:
          OUTCOMES: ${{ toJson(steps.maybe-fail.outcome) }}
          MESSAGE: ${{ steps.maybe-fail.outcome == 'failure' && "success" || "failure" }}
