name: dynamic-message

on:
  workflow_dispatch:
  push:

jobs:
  dynamic-message:
    runs-on: ubuntu-latest

    steps:

      - name: Maybe fail
        id: maybe-fail
        continue-on-error: true
        run: |
          echo "This is a deliberate fail"

      - name: Show message
        run: |
          echo "Outcomes: $OUTCOMES"
          echo "Message: $MESSAGE"
        env:
          OUTCOMES: ${{ toJson(steps.maybe-fail.outcome) }}
          MESSAGE: ${{ steps.maybe-fail.outcome == 'success' && 'success' || 'failure' }}
