name: my workflow

on:
  workflow_dispatch:
  push:

jobs:
  my_job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get response templates
        id: get-response-templates
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Deliberate fail
        id: deliberate-fail
        continue-on-error: true
        run: |
          echo "This is a deliberate fail"

      - name: Show all step results
        run: |
          echo $OVERALL
        env:
          OVERALL: ${{ toJson(steps.*.outcome) }}

      - name: Build message - step results
        if: true
        id: build-message-step-results
        uses: skills/action-text-variables@v1
        with:
          template-file: skills-response-templates/step-feedback/step-results.md
          template-vars: >
            {
              "step_number": 1,
              "passed": ${{ steps.*.outcome == 'success' }},
              "results_table": [
                {
                  "name": "Overall",
                  "passed": ${{ steps.*.outcome == 'success' }},
                  "message": "${{ steps.*.outcome == 'success' }}"
                },
                {
                  "name": "Checkout",
                  "passed": ${{ steps.checkout.outcome == 'success' }},
                  "message": "${{ steps.checkout.outcome == 'success' }}"
                },
                {
                  "name": "Deliberate fail",
                  "passed": ${{ steps.deliberate-fail.outcome == 'success' }},
                  "message": "${{ steps.deliberate-fail.outcome == 'success' }}"
                }
              ],
              "tips": [
                "???",
                "???"
              ]
            }

      - name: Check if all previous steps were successful
        run: |
          echo $UPDATED_TEXT
        env:
          UPDATED_TEXT: ${{ steps.build-message-step-results.outputs.updated-text }}
