name: my workflow

on:
  workflow_dispatch:
  push:

jobs:
  my_job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Deliberate pass
        id: deliberate-pass
        continue-on-error: true
        run: |
          echo "This is a deliberate pass"

      - name: Maybe fail (fail)
        id: maybe-fail
        continue-on-error: true
        run: |
          echo "This is a deliberate fail"
          exit 1

      - name: Show all step results
        run: |
          echo "Outcomes: $OUTCOMES"
          echo "Contains false: $CONTAINS_FALSE"
          echo "Contains no false: $CONTAINS_NO_FALSE"
        env:
          OUTCOMES: ${{ toJson(steps.*.outcome) }}
          CONTAINS_FALSE: ${{ contains(steps.*.outcome, 'false') }}
          CONTAINS_NO_FALSE: ${{ !contains(steps.*.outcome, 'false') }}

      - name: Build message - step results
        if: false
        id: build-message-step-results
        uses: skills/action-text-variables@v1
        with:
          template-file: skills-response-templates/step-feedback/step-results.md
          template-vars: >
            {
              "step_number": 1,
              "passed": ${{ !contains(steps.*.outcome, 'false') }},
              "results_table": [
                {
                  "name": "Overall",
                  "passed": ${{ steps.*.outcome == 'success' }},
                  "message": "${{ steps.*.outcome == 'success' }}"
                },
                {
                  "name": "Deliberate pass",
                  "passed": ${{ steps.deliberate-pass.outcome == 'success' }},
                  "message": "${{ steps.deliberate-pass.outcome == 'success' }}"
                },
                {
                  "name": "Deliberate fail",
                  "passed": ${{ steps.maybe-fail.outcome == 'success' }},
                  "message": "${{ steps.maybe-fail.outcome == 'success' }}"
                }
              ],
              "tips": [
                "???",
                "???"
              ]
            }

      - name: Show on console
        if: false
        run: |
          echo $UPDATED_TEXT
        env:
          UPDATED_TEXT: ${{ steps.build-message-step-results.outputs.updated-text }}
