name: my workflow

on:
  workflow_dispatch:
jobs:
  my_job:
    name: Check if secret scanning is enabled
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Deliberate fail
        continue-on-error: true
        run: |
          echo "This is a deliberate fail"
          exit 1

      - name: Check if all previous steps were successful

        run: |
          exit $OVERALL
        env:
          OVERALL: ${{ toJson(steps.*.outcome) }}
