name: my workflow

on:
  workflow_dispatch:
  push:

jobs:
  my_job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Deliberate fail
        id: deliberate-fail
        continue-on-error: true
        run: |
          echo "This is a deliberate fail"
          exit 1

      - name: Check if all previous steps were successful
        run: |
          echo $OVERALL
        env:
          OVERALL: ${{ toJson(steps.*.outcome) }}
