name: my workflow

on:
  workflow_dispatch:
  push:

jobs:
  get_templates:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates 1
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Show templates
        run: |
          echo "Templates:"
          ls -R skills-response-templates

      - name: Get exercise toolkit templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          ref: v0.3.0
          sparse-checkout: |
            markdown-templates
          path: exercise-toolkit

      - name: Show templates
        run: |
          echo "Templates:"
          ls -R exercise-toolkit/markdown-templates

