name: Weekly Snippets

permissions:
  contents: read
  issues: write

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 4" # Every Thursday at 12:00 AM

jobs:
  weekly-snippets:
    name: Create Weekly Snippet Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Close previous week's issue
        run: |
          issue_number=$(gh issue list --label "weekly-snippet" --limit 1 --sort created --json number --jq '.[0].number')
          if [ -n "$issue_number" ]; then
            gh issue close $issue_number
          fi
      
      - name: Create this week's issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/weekly-snippets-template.md
